name: Code checks

on: 
  push:
    branches: [ main ]
  pull_requests:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Run flake8
        run:  poetry run flake8 src/forest_ml
      - name: Run mypy
        run:  poetry run mypy src/forest_ml      
      - name: Run black
        run:  poetry run black src/forest_ml
      